language: java
bundler_args: --retry 1
os: linux
sudo: false

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "ajg6cm5798rx2DHmwhie9VQko8J6OIiDDRwrOoP1zHLodmcjtJEhtvAnPpSEHjEINunLpOyhVncYpIPiSQW8Fq5L9FMtmDHaQpXPB1RZX24VGEVdB1BjUAQqe1c9FrNHjP7c/UdR6xXUkI83mejTlZI9VgVXpTpfG5geElo/2Ewhl/VsWinRKPDeE9fqdRZrw7eKfrNNOBn9PCqxBTdIsY/ed3eKQBXSdYsM5bIk/VE2UL3v7SYagKP5/B0sDDEbxLps4mVPC57yAx8DFm2LegqwXxh0RXNjnfuyCPLrx7CmP3p5P5Q/oDXaX48/wQd9bqfIxCfnLwaYjHpki8d6XJ85J3DLU5QgqQkUuJjDwvTbs5k1Z8QY5y2gTnEiw9EmAzDbi3NyTjfBwgioULB9I02+vGIv/SNuENxRaODbnGDCdw0071J9TiLGF5bzezAvXDgdGdQD/uGWbaCtaUhzHCbpbgEc7DkEgSmz96rORlR45JB/SBBb0KWi6Cf5I/nwCLsYCNaqI9fricpwU9YfB19YE/xPFY7YirkPHAiQRhL8fgD+u473R/b5PjHpYgQF9nfZG5tZXGRFdaVm4RcVawy1n2MXmiWxg8ZUS3gB5pgErpapH9S4LLk8ESpa/ciPYfMmWcAurv6ziSkdnh7oE8zgNodFDt/StHRrxeEndV4="

install: true

script:
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.scm.disabled=true -Dsonar.language=java

cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache

before_cache:
  - rm -rf $HOME/.m2/repository/ru/r2cloud/

before_deploy:
  - mvn -Djavafx.platform=mac-aarch64 assembly:single
  - mvn -Djavafx.platform=mac assembly:single
  - mvn -Djavafx.platform=linux assembly:single
  - mvn -Djavafx.platform=win assembly:single

deploy:
  provider: releases
  api_key:
    secure: "xydSkI4RpT7KrrUqnL325tqQHtkQl/UrGKylaWaoO3i9KrMkWGlPDen9tJ9M4WQGC0Kw8OmgOxUGQRabVJIphQdMrQXiLm2wRs01YlsIQSyoAY1JuQxEBnDizfLqDSjIm7nlp4HqOFy0HsPRztcezkxgiQO7uivr9NP+mR7WsNQDsnq/s0egq8/Ae0frr9SJJ7KUjK/ZRKjmNaGjbbCg7T+jjboORd1gUc+5+W6okfePSiH14S3ZHud++KA4P+RRyBmFhmfaFSmj3083+j2YP8y/FtFmNbqtbT5Pq/6HjY6LMOLW+oV17U203sy7Fh7FhF3hl8zlaDJl1fGHEADt9HcybWYmY8m22h0xJlrRrEBaUp5yISpFzfEIL0lS4HBqObYGmGTYt+oJ8f31cGbtug3DPOkioE+u7FyrihOzXUi2OJ1rpHdWLe+56T+GCMNOYwfDVZ6L6mAS0tZHqKe2UVc3vr8cWDqk2tSTGth+zK1fWlMveCxoJ9fIDAiJMSeoWfNV2SOJb7h9R5lpi1XNaf4GRcT8uM5qyOHDxNF8bpt6+lfo7kSaXXvS5ks9+AgikFgArRkJCAO7VKLweSo5MW321024dfSOZF1m3GaSWHpcF40l6bko6yXKM35av29ZRI65RojrU+dbmaYiWkHPQmAo6E/2GsejUOungE+6u3Q="
  file_glob: true
  file: "target/rtlSpectrum_*.jar"
  skip_cleanup: true
  on:
    tags: true